#!/bin/bash
#PBS -N thermal_noise_removal
#PBS -M martinsd@uni-potsdam.de
#PBS -j oe
#PBS -l ncpus=1
#PBS -l nodes=1:ppn=1
#PBS -l walltime=1:00:00
#PBS -l mem=20gb
cd /users/stud09/martinsd/proj/buhayra

source activate buhayra

export JAVA_TOOL_OPTIONS="-Xmx16g"
export _JAVA_OPTIONS="-Xmx18g -Xss2m"

/users/stud09/martinsd/local/snap/bin/gpt ThermalNoiseRemoval -SsourceProduct=/mnt/scratch/martinsd/test_dataset/s1a_scenes/in/S1A_IW_GRDH_1SDV_20180109T082617_20180109T082642_020075_02237C_A489.zip -PselectedPolarisations=VV -PremoveThermalNoise=true -t /mnt/scratch/martinsd/test_dataset/s1a_scenes/in/S1A_IW_GRDH_1SDV_20180109T082617_20180109T082642_020075_02237C_A489.dim
